import os
import subprocess

import pandas as pd


def SynthesizeMealy(file_path):
    inputs = (
        subprocess.run(
            ["syfco", "--print-input-signals", file_path],
            capture_output=True,
            text=True,
            check=True,
        )
        .stdout.replace(" ", "")
        .strip()
    )

    outputs = (
        subprocess.run(
            ["syfco", "--print-output-signals", file_path],
            capture_output=True,
            text=True,
            check=True,
        )
        .stdout.replace(" ", "")
        .strip()
    )

    APs = ",".join([inputs, outputs]) if outputs else inputs

    subprocess.run(
        f"ltlsynt --hide-status --tlsf {file_path} > System.hoa", shell=True, check=True
    )
    subprocess.run(
        f"ltlsynt --hide-status --tlsf {file_path} --dot > System.dot",
        shell=True,
        check=True,
    )

    return APs, inputs, outputs


def GenerateTraces(
    dot_file, aps, num_traces=100, trace_length=10, output_file="Training_Dataset.txt"
):
    subprocess.run(
        [
            "python",
            "Dot_Trace_Generator.py",
            dot_file,
            "--fmt",
            "dot",
            "--aps",
            aps,
            "-n",
            str(num_traces),
            "-l",
            str(trace_length),
            "--cycle",
            "--out",
            output_file,
        ],
        check=True,
    )


def CheckTraces(hoa_file, data_file):
    """Run Trace_Checker and parse acceptance percentage from stdout."""
    result = subprocess.run(
        ["python", "Trace_Checker.py", hoa_file, data_file],
        capture_output=True,
        text=True,
        check=True,
    )
    # Look for the line with "Acceptance %:"
    acc = None
    for line in result.stdout.splitlines():
        if line.startswith("Acceptance %:"):
            acc = float(line.split(":")[1].strip().replace("%", ""))
    return acc


def PassiveLearning(data_file, inputs, outputs):
    subprocess.run(
        ["python", "Passive_Mealy_Learning.py", data_file, inputs, outputs], check=True
    )

    subprocess.run(
        "autfilt Training_Dataset.hoa --dot > Training_Dataset.dot",
        shell=True,
        check=True,
    )


def PassivePipeline(tlsf_file, num_traces=10, length=10, test_traces=1000):
    """Full passive learning pipeline with accuracy tracking."""
    APs, Inputs, Outputs = SynthesizeMealy(tlsf_file)

    # Training: use num_traces
    GenerateTraces("System.dot", APs, num_traces, length, "Training_Dataset.txt")
    print("Validating Traces Generated By Master Dot File")
    CheckTraces("System.hoa", "Training_Dataset.txt")

    print("Passive Learning")
    PassiveLearning("Training_Dataset.txt", Inputs, Outputs)

    # Testing: always use fixed test_traces count
    GenerateTraces("Training_Dataset.dot", APs, test_traces, length, "Test_Dataset.txt")
    print(f"Check Recovered Trace ({test_traces} test traces)")
    acc = CheckTraces("System.hoa", "Test_Dataset.txt")

    return acc


def ActiveLearning(tlsf_file):
    inputs = (
        subprocess.run(
            ["syfco", "--print-input-signals", tlsf_file],
            capture_output=True,
            text=True,
            check=True,
        )
        .stdout.replace(" ", "")
        .strip()
    )

    outputs = (
        subprocess.run(
            ["syfco", "--print-output-signals", tlsf_file],
            capture_output=True,
            text=True,
            check=True,
        )
        .stdout.replace(" ", "")
        .strip()
    )

    subprocess.run(
        f"ltlsynt --hide-status --tlsf {tlsf_file} --dot > System.dot",
        shell=True,
        check=True,
    )

    result = subprocess.run(
        [
            "python",
            "active_learning.py",
            "System.dot",
            "--inputs",
            inputs,
            "--outputs",
            outputs,
            "--algorithm",
            "lstar",
            "--eq",
            "random_walk",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print("ERROR: active_learning.py failed")
        print(f"STDERR: {result.stderr}")
        return None

    # Extract membership queries from the learning algorithm section
    queries_learning = None
    queries_eq = None

    for line in result.stdout.splitlines():
        if "# Membership Queries" in line and queries_learning is None:
            # First occurrence is from Learning Algorithm section
            queries_learning = int(line.split(":")[-1].strip())
        elif "# Membership Queries" in line and queries_learning is not None:
            # Second occurrence is from Equivalence Query section
            queries_eq = int(line.split(":")[-1].strip())
            break

    if queries_learning is not None and queries_eq is not None:
        queries_total = queries_learning + queries_eq
        print(
            f"Queries - Learning: {queries_learning}, EQ: {queries_eq}, Total: {queries_total}"
        )
        return queries_total
    else:
        print("Could not extract query counts")
        return None


if __name__ == "__main__":
    directory = "./TestSet/SyntCompBenchMarks"

    # Initialize results list
    results = []

    for file in os.listdir(directory):
        if not file.endswith(".tlsf"):
            continue

        full_path = os.path.join(directory, file)
        print(f"\n[+] Processing: {file}")

        queries = ActiveLearning(full_path)

        results.append({"file": file, "queries_total": queries})

        print(f"[✓] {file}: {queries} queries\n")

    # Create DataFrame
    df = pd.DataFrame(results)

    # Save to CSV
    output_csv = "active_learning_results.csv"
    df.to_csv(output_csv, index=False)

    print(f"Results saved to: {output_csv}")
    print(df)

    # sweep settings
    trace_lengths = [20]  # keep length fixed
    trace_counts = [1000, 5000]  # vary num_traces

    csv_path = "pipeline_results.csv"

    # Load existing results if present
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
    else:
        df = pd.DataFrame(
            columns=["file", "num_traces", "length", "samples", "accuracy"]
        )

    all_results = []

    for num_traces in trace_counts:
        for length in trace_lengths:
            samples = num_traces * length
            for file in os.listdir(directory):
                if not file.endswith(".tlsf"):
                    continue

                # skip if this combo already exists in df
                if ((df["file"] == file) & (df["samples"] == samples)).any():
                    print(f"[!] Skipping {file} with {samples} samples (already done)")
                    continue

                full_path = os.path.join(directory, file)
                print(
                    f"\n[+] Running pipeline for {full_path} with {num_traces} traces, length {length}"
                )
                acc = PassivePipeline(full_path, num_traces, length)

                all_results.append(
                    {
                        "file": file,
                        "num_traces": num_traces,
                        "length": length,
                        "samples": samples,
                        "accuracy": acc,
                    }
                )

    # Merge new results with old
    if all_results:
        df = pd.concat([df, pd.DataFrame(all_results)], ignore_index=True)

    # sort by file and then sample size
    df = df.sort_values(by=["file", "samples"]).reset_index(drop=True)

    # Group by file and samples, compute average accuracy
    summary = (
        df.groupby(["file", "samples"], as_index=False)["accuracy"]
        .mean()
        .rename(columns={"accuracy": "average_accuracy"})
    )

    # Save to CSV
    summary.to_csv("summary_accuracy.csv", index=False)

    print("Saved grouped summary to summary_accuracy.csv")
    # TODO
    # CALL ACTIVE LEARNING LOOP HERE
