import os
import subprocess

import pandas as pd


def SynthesizeMealy(file_path):
    inputs = (
        subprocess.run(
            ["syfco", "--print-input-signals", file_path],
            capture_output=True,
            text=True,
            check=True,
        )
        .stdout.replace(" ", "")
        .strip()
    )

    outputs = (
        subprocess.run(
            ["syfco", "--print-output-signals", file_path],
            capture_output=True,
            text=True,
            check=True,
        )
        .stdout.replace(" ", "")
        .strip()
    )

    APs = ",".join([inputs, outputs]) if outputs else inputs

    subprocess.run(
        f"ltlsynt --hide-status --tlsf {file_path} > System.hoa", shell=True, check=True
    )
    subprocess.run(
        f"ltlsynt --hide-status --tlsf {file_path} --dot > System.dot",
        shell=True,
        check=True,
    )

    return APs, inputs, outputs


def GenerateTraces(
    dot_file, aps, num_traces=100, trace_length=10, output_file="Training_Dataset.txt"
):
    subprocess.run(
        [
            "python",
            "dot_trace_generator.py",
            dot_file,
            "--fmt",
            "dot",
            "--aps",
            aps,
            "-n",
            str(num_traces),
            "-l",
            str(trace_length),
            "--cycle",
            "--out",
            output_file,
        ],
        check=True,
    )


def CheckTraces(hoa_file, data_file):
    """Run Trace_Checker and parse acceptance percentage from stdout."""
    result = subprocess.run(
        ["python", "trace_Checker.py", hoa_file, data_file],
        capture_output=True,
        text=True,
        check=True,
    )
    # Look for the line with "Acceptance %:"
    acc = None
    for line in result.stdout.splitlines():
        if line.startswith("Acceptance %:"):
            acc = float(line.split(":")[1].strip().replace("%", ""))
    return acc


def PassiveLearning(data_file, inputs, outputs):
    subprocess.run(
        ["python", "Passive_Mealy_Learning.py", data_file, inputs, outputs], check=True
    )

    subprocess.run(
        "autfilt Training_Dataset.hoa --dot > Training_Dataset.dot",
        shell=True,
        check=True,
    )


def PassivePipeline(tlsf_file, num_traces=10, length=10):
    """Full passive learning pipeline with accuracy tracking."""
    APs, Inputs, Outputs = SynthesizeMealy(tlsf_file)

    GenerateTraces("System.dot", APs, num_traces, length, "Training_Dataset.txt")
    print("Validating Traces Generated By Master Dot File")
    CheckTraces("System.hoa", "Training_Dataset.txt")

    print("Passive Learning")
    PassiveLearning("Training_Dataset.txt", Inputs, Outputs)

    GenerateTraces("Training_Dataset.dot", APs, num_traces, length, "Test_Dataset.txt")
    print("Check Recovered Trace")
    acc = CheckTraces("System.hoa", "Test_Dataset.txt")

    return acc


def ActiveLearning(tlsf_file):
    inputs = (
        subprocess.run(
            ["syfco", "--print-input-signals", tlsf_file],
            capture_output=True,
            text=True,
            check=True,
        )
        .stdout.replace(" ", "")
        .strip()
    )

    outputs = (
        subprocess.run(
            ["syfco", "--print-output-signals", tlsf_file],
            capture_output=True,
            text=True,
            check=True,
        )
        .stdout.replace(" ", "")
        .strip()
    )

    result = subprocess.run(
        [
            "python",
            "ActiveLearning.py",
            "controller.dot",
            "--inputs",
            inputs,
            "--outputs",
            outputs,
            "--algorithm",
            "lstar",
            "--eq",
            "random_walk",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    print("STDOUT:\n", result.stdout)
    print("STDERR:\n", result.stderr)
    subprocess.run(
        "autfilt controller_learned.hoa --dot > controller_learned.dot",
        shell=True,
        check=True,
    )


if __name__ == "__main__":
    directory = "/Users/will/github/Automata_SSM_Learning/TestSet/SyntCompBenchMarks/"

    # sweep settings
    trace_lengths = [10]  # keep length fixed
    trace_counts = [5, 10, 20, 50, 100]  # vary num_traces

    csv_path = "pipeline_results.csv"

    # Load existing results if present
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
    else:
        df = pd.DataFrame(
            columns=["file", "num_traces", "length", "samples", "accuracy"]
        )

    all_results = []

    for num_traces in trace_counts:
        for length in trace_lengths:
            samples = num_traces * length
            for file in os.listdir(directory):
                if not file.endswith(".tlsf"):
                    continue

                # skip if this combo already exists in df
                if ((df["file"] == file) & (df["samples"] == samples)).any():
                    print(f"[!] Skipping {file} with {samples} samples (already done)")
                    continue

                full_path = os.path.join(directory, file)
                print(
                    f"\n[+] Running pipeline for {full_path} with {num_traces} traces, length {length}"
                )
                acc = PassivePipeline(full_path, num_traces, length)

                all_results.append(
                    {
                        "file": file,
                        "num_traces": num_traces,
                        "length": length,
                        "samples": samples,
                        "accuracy": acc,
                    }
                )

    # Merge new results with old
    if all_results:
        df = pd.concat([df, pd.DataFrame(all_results)], ignore_index=True)

    # sort by file and then sample size
    df = df.sort_values(by=["file", "samples"]).reset_index(drop=True)

    # Group by file and samples, compute average accuracy
    summary = (
        df.groupby(["file", "samples"], as_index=False)["accuracy"]
        .mean()
        .rename(columns={"accuracy": "average_accuracy"})
    )

    # Save to CSV
    summary.to_csv("summary_accuracy.csv", index=False)

    print("Saved grouped summary to summary_accuracy.csv")
    # TODO
    # CALL ACTIVE LEARNING LOOP HERE
