[hoax]
name = "Random trace generator"
version = 1
default-driver = "flip"

[input]
type = "random"

[outputs]
mode = "auto"

[runner]
bound = 10

[behavior]
on_nondeterminism = "explore"
on_deadlock = "error"

